[package]
name = "task-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
domain = { path = "../domain" }
persistence-sqlite = { path = "../persistence-sqlite" }
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
